# Generated by Django 4.2.5 on 2023-09-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_alter_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=25, unique=True)),
                ('slug', models.SlugField(max_length=25)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('soft_deleted', models.BooleanField(default=False)),
                ('Category_image', models.ImageField(blank=True, upload_to='photos/category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='photos/product')),
                ('image2', models.ImageField(null=True, upload_to='photos/product')),
                ('image3', models.ImageField(null=True, upload_to='photos/product')),
                ('image4', models.ImageField(null=True, upload_to='photos/product')),
                ('image5', models.ImageField(null=True, upload_to='photos/product')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quatity', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('soft_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.category')),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.product_image')),
            ],
        ),
    ]
