# Generated by Django 4.2.5 on 2023-09-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_category_product_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/product', verbose_name='Product Image 1'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image2',
            field=models.ImageField(null=True, upload_to='photos/product', verbose_name='Product Image 2'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image3',
            field=models.ImageField(null=True, upload_to='photos/product', verbose_name='Product Image 3'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image4',
            field=models.ImageField(null=True, upload_to='photos/product', verbose_name='Product Image 4'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image5',
            field=models.ImageField(null=True, upload_to='photos/product', verbose_name='Product Image 5'),
        ),
    ]
