# Generated by Django 4.2.5 on 2023-10-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0004_alter_product_image_image_alter_product_image_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quatity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='product_image',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='default_image.jpg', upload_to='product_images', verbose_name='Product Image 1'),
        ),
        migrations.AddField(
            model_name='product_image',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='userside.product'),
        ),
    ]
