# Generated by Django 4.2.5 on 2023-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0005_rename_quatity_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_image',
            field=models.ImageField(upload_to='photos/category'),
        ),
    ]
