# Generated by Django 4.2.5 on 2023-10-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0006_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='photos/product'),
        ),
    ]
