# Generated by Django 4.2.5 on 2023-10-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_shipping_address_order_address_line_1_and_more'),
        ('userside', '0013_addressbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressBook',
        ),
    ]
