# Generated by Django 4.2.5 on 2023-11-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0018_alter_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
