# Generated by Django 4.2.5 on 2023-11-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0021_rename_text_review_comment_product_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
