# Generated by Django 4.2.5 on 2023-11-13 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0022_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
