# Generated by Django 4.2.5 on 2023-11-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userside', '0015_addressbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('discount_percentage', models.IntegerField(default=0)),
                ('product_offer_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('product_offer_image', models.ImageField(null=True, upload_to='photos/offerimages')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ManyToManyField(to='userside.product')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('discount_percentage', models.IntegerField(default=0)),
                ('category_offer_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category_offer_image', models.ImageField(null=True, upload_to='photos/offerimages')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.category')),
            ],
        ),
    ]
