# Generated by Django 4.2.5 on 2023-10-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userdetails_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='DOB',
            new_name='date_of_birth',
        ),
    ]
