# Generated by Django 4.2.5 on 2023-10-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0012_variation'),
        ('orders', '0002_paymentmethod_payment_payment_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variation',
            field=models.ManyToManyField(to='userside.variation'),
        ),
    ]
