# Generated by Django 4.2.5 on 2023-11-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_coupon_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_discount',
            field=models.IntegerField(null=True),
        ),
    ]
