# Generated by Django 4.2.5 on 2023-11-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_coupon_discount_order_wallet_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='wallet_discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
