# Generated by Django 4.2.5 on 2023-11-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
